/**
 * Offline install.
 *
 * "More and more professional 3D software is now only available on
 * subscription... tools also phone home every few days." "Perpetual means
 * never ending... will no longer allow me to use my software by refusing to
 * activate it."
 *
 * The answer this application can give is not a promise in a licence, it is a
 * property of the software: every file it needs is cached on first visit, and
 * after that it opens and runs with the network off, forever, with no check
 * and nothing to activate. There is no server to ask for permission because
 * there is no server.
 *
 * GENERATED by tools/build-sw.mjs. Do not edit by hand: a hand-written cache
 * list is a list that goes stale, and a stale list means the app works offline
 * until the day somebody adds a module. Regenerate it instead.
 *
 * Cache-first on purpose. A design tool that stalls because a network is slow
 * is worse than one that is a deploy behind, and the fetch below still
 * refreshes the cache in the background, so the next open is current.
 */
const VERSION = 'tessercadina-ff6054765e53';
const FILES = [
  "assets/favicon.svg",
  "index.html",
  "src/boot.js",
  "src/core/bus.js",
  "src/core/csg-core.js",
  "src/core/csg-pool.js",
  "src/core/csg-worker.js",
  "src/core/csg.js",
  "src/core/doc.js",
  "src/core/expr.js",
  "src/core/geometry.js",
  "src/core/i18n.js",
  "src/core/lang-interface.js",
  "src/core/lang-prose.js",
  "src/core/rebuild.js",
  "src/draft/draft.js",
  "src/draft/dxf.js",
  "src/draft/entity.js",
  "src/intel/brief.js",
  "src/intel/configs.js",
  "src/intel/cost.js",
  "src/intel/deviation.js",
  "src/intel/doctor.js",
  "src/intel/drawing.js",
  "src/intel/fasteners.js",
  "src/intel/history.js",
  "src/intel/hygiene.js",
  "src/intel/interfere.js",
  "src/intel/macros.js",
  "src/intel/merge.js",
  "src/intel/offline.js",
  "src/intel/process.js",
  "src/intel/recognise.js",
  "src/intel/release.js",
  "src/intel/section.js",
  "src/intel/speak.js",
  "src/intel/spec.js",
  "src/intel/standards.js",
  "src/intel/tessellate.js",
  "src/intel/tolerance.js",
  "src/intel/why.js",
  "src/intel/zip.js",
  "src/io/io.js",
  "src/main.js",
  "src/sim/recorder.js",
  "src/sim/sim.js",
  "src/ui/commands.js",
  "src/ui/icons.js",
  "src/ui/inspector.js",
  "src/ui/menus.js",
  "src/ui/mobile.js",
  "src/ui/operators.js",
  "src/ui/shell.js",
  "src/ui/timelineui.js",
  "src/ui/tree.js",
  "src/view/viewport.js",
  "styles/app.css",
  "vendor/BufferGeometryUtils.js",
  "vendor/GLTFExporter.js",
  "vendor/OBJExporter.js",
  "vendor/OBJLoader.js",
  "vendor/OrbitControls.js",
  "vendor/RoomEnvironment.js",
  "vendor/STLExporter.js",
  "vendor/STLLoader.js",
  "vendor/TextureUtils.js",
  "vendor/TransformControls.js",
  "vendor/three.module.js"
];

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(VERSION);
    // One failed file must not fail the whole install, or a single renamed
    // asset leaves the user with no offline copy at all.
    await Promise.all(FILES.map(f => cache.add(new Request(f, { cache: 'reload' })).catch(() => {})));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== VERSION && key.startsWith('tessercadina-')) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   // nothing else is ours to serve

  e.respondWith((async () => {
    const cache = await caches.open(VERSION);
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) {
      // Refresh in the background so the next open is current, without ever
      // making this open wait for a network.
      fetch(req).then(res => { if (res.ok) cache.put(req, res.clone()); }).catch(() => {});
      return hit;
    }
    try {
      const res = await fetch(req);
      if (res.ok) cache.put(req, res.clone());
      return res;
    } catch {
      // Offline and not cached: a navigation still gets the app shell, so the
      // user lands in the application rather than on a browser error page.
      if (req.mode === 'navigate') {
        const shell = await cache.match('index.html');
        if (shell) return shell;
      }
      return new Response('Offline and not in the cache.', { status: 504, statusText: 'Offline' });
    }
  })());
});

self.addEventListener('message', (e) => {
  if (e.data === 'version') e.source?.postMessage({ version: VERSION, files: FILES.length });
});
