/**
 * Generate the service worker's file list from what is actually on disk.
 *
 * A hand-written cache list is a list that goes stale, and a stale list means
 * the app works offline until the day somebody adds a module. So the list is
 * generated, and the generated file is committed so the site stays a static
 * site with no build step for anyone who just wants to serve it.
 *
 *   node tools/build-sw.mjs
 */
import { readdirSync, statSync, writeFileSync, readFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

// `fileURLToPath`, not `.pathname`. On Windows a file URL's pathname is
// `/D:/a/repo/...` — a leading slash before the drive letter — which is not a
// path any filesystem call accepts. Every read against it fails, which is how
// four suites came to fail on the Windows runner while passing everywhere else.
const root = fileURLToPath(new URL('..', import.meta.url)).replace(/[\\/]$/, '');
const INCLUDE_DIRS = ['src', 'styles', 'vendor', 'assets'];
const INCLUDE_FILES = ['index.html'];
const SKIP = /(^|\/)(node_modules|\.git|docs|tools)(\/|$)|\.map$|LICENSE/;

const walk = (dir, out = []) => {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const rel = relative(root, full).split(sep).join('/');
    if (SKIP.test(rel)) continue;
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(rel);
  }
  return out;
};

const files = [...INCLUDE_FILES];
for (const d of INCLUDE_DIRS) {
  try { walk(join(root, d), files); } catch { /* an optional directory */ }
}
files.sort();

// The version is a hash of the contents, so a deploy that changes nothing
// leaves the cache alone and one that changes anything replaces it wholesale.
const h = createHash('sha256');
for (const f of files) h.update(f).update(readFileSync(join(root, f)));
const version = h.digest('hex').slice(0, 12);

const body = `/**
 * Offline install.
 *
 * "More and more professional 3D software is now only available on
 * subscription... tools also phone home every few days." "Perpetual means
 * never ending... will no longer allow me to use my software by refusing to
 * activate it."
 *
 * The answer this application can give is not a promise in a licence, it is a
 * property of the software: every file it needs is cached on first visit, and
 * after that it opens and runs with the network off, forever, with no check
 * and nothing to activate. There is no server to ask for permission because
 * there is no server.
 *
 * GENERATED by tools/build-sw.mjs. Do not edit by hand: a hand-written cache
 * list is a list that goes stale, and a stale list means the app works offline
 * until the day somebody adds a module. Regenerate it instead.
 *
 * Cache-first on purpose. A design tool that stalls because a network is slow
 * is worse than one that is a deploy behind, and the fetch below still
 * refreshes the cache in the background, so the next open is current.
 */
const VERSION = 'tessercad-${version}';
const FILES = ${JSON.stringify(files, null, 2).replace(/\n/g, '\n')};

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(VERSION);
    // One failed file must not fail the whole install, or a single renamed
    // asset leaves the user with no offline copy at all.
    await Promise.all(FILES.map(f => cache.add(new Request(f, { cache: 'reload' })).catch(() => {})));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== VERSION && key.startsWith('tessercad-')) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   // nothing else is ours to serve

  e.respondWith((async () => {
    const cache = await caches.open(VERSION);
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) {
      // Refresh in the background so the next open is current, without ever
      // making this open wait for a network.
      fetch(req).then(res => { if (res.ok) cache.put(req, res.clone()); }).catch(() => {});
      return hit;
    }
    try {
      const res = await fetch(req);
      if (res.ok) cache.put(req, res.clone());
      return res;
    } catch {
      // Offline and not cached: a navigation still gets the app shell, so the
      // user lands in the application rather than on a browser error page.
      if (req.mode === 'navigate') {
        const shell = await cache.match('index.html');
        if (shell) return shell;
      }
      return new Response('Offline and not in the cache.', { status: 504, statusText: 'Offline' });
    }
  })());
});

self.addEventListener('message', (e) => {
  if (e.data === 'version') e.source?.postMessage({ version: VERSION, files: FILES.length });
});
`;

writeFileSync(join(root, 'sw.js'), body);
console.log(`sw.js: ${files.length} files, version ${version}`);
